name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply --auto-approve

      - name: Set up SSH connection
        run: ssh-keyscan -H ${{ env.INSTANCE_IP }} >> ~/.ssh/known_hosts

      - name: Set up Ansible
        uses: appleboy/ansible-action@v2
        with:
          playbook: playbook.yml
          inventory: ${{ env.INSTANCE_IP }},

      - name: Cleanup
        run: terraform destroy --auto-approve
